backend/controllers/AuthController.php
<?php

namespace backend\controllers;

use common\models\User;
use Yii;
use yii\helpers\Url;
use common\models\Task;
use backend\models\TaskSearch;
use yii\helpers\VarDumper;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * TaskController implements the CRUD actions for Task model.
 */
class AuthController extends Controller
{

    public function actionLogin(){

        $this->layout = 'login';
        $model = new User();
        $model->setScenario('login');

        if(\Yii::$app->request->method == 'GET'){
            return $this->render('login', ['model' => $model]);
        }

        $model->attributes = \Yii::$app->request->post('User');
        if($model->validate()){
            Yii::$app->user->login(User::findOne(['username' => $model->username]));

            return $this->redirect('/');
        } else{
            return $this->render('login', ['model' => $model]);
        }

    }

    public function behaviors()
    {
        return [
            'access' => [
                'class' => \yii\filters\AccessControl::class,
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['adminPanel']
                    ],
                ]
            ]
        ];
    }

    public function actionLogout(){
        Yii::$app->user->logout();
        return $this->redirect(Url::toRoute('login'));
    }
}

backend/controllers/TaskController.php
<?php

namespace backend\controllers;

use Yii;
use common\models\Task;
use backend\models\TaskSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * TaskController implements the CRUD actions for Task model.
 */
class TaskController extends Controller
{
    /**
     * @inheritdoc
     */

    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
            'access' => [
                'class' => \yii\filters\AccessControl::class,
                'rules' => [
                    [
                        'actions' => ['index', 'view', 'create', 'update', 'delete'],
                        'allow' => true,
                        'roles' => ['adminPanel']
                    ],
                ]
            ]
//            [
//                'class' => 'common\filters\RbacFilter',
//                'action_permission' =>[
//                    'index' => 'adminPanel',
//                    'view' => 'adminPanel',
//                    'create' => 'adminPanel',
//                    'update' => 'adminPanel',
//                    'delete' => 'adminPanel',
//                ]
//            ],
        ];
    }

    /**
     * Lists all Task models.
     * @return mixed
     */
    public function actionIndex($tasklist_id = null)
    {
        $searchModel = new TaskSearch();

        $params = Yii::$app->request->queryParams;
        if($tasklist_id != null){
            $params['TaskSearch']['tasklist_id'] = $tasklist_id;
        }

        $dataProvider = $searchModel->search($params);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Task model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Task model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Task();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing Task model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Task model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Task model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Task the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Task::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

backend/controllers/TaskListController.php
<?php

namespace backend\controllers;

use Yii;
use common\models\TaskList;
use backend\models\TaskListSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * TaskListController implements the CRUD actions for TaskList model.
 */
class TaskListController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
            'access' => [
                'class' => \yii\filters\AccessControl::class,
                'rules' => [
                    [
                        'actions' => ['index', 'view', 'create', 'update', 'delete'],
                        'allow' => true,
                        'roles' => ['adminPanel']
                    ],
                ]
            ]
//            [
//                'class' => 'common\filters\RbacFilter',
//                'action_permission' =>[
//                    'index' => 'adminPanel',
//                    'view' => 'adminPanel',
//                    'create' => 'adminPanel',
//                    'update' => 'adminPanel',
//                    'delete' => 'adminPanel',
//                ]
//            ],
        ];
    }

    /**
     * Lists all TaskList models.
     * @return mixed
     */
    public function actionIndex($user_id = null)
    {
        $searchModel = new TaskListSearch();
        $params = Yii::$app->request->queryParams;

        if($user_id != null){
            $params['TaskListSearch']['user_id'] = $user_id;
        }

        $dataProvider = $searchModel->search($params);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single TaskList model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new TaskList model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new TaskList();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing TaskList model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing TaskList model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the TaskList model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return TaskList the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = TaskList::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

backend/controllers/UserController.php
<?php

namespace backend\controllers;

use common\models\User;
use Yii;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;


class UserController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
            'access' => [
                'class' => \yii\filters\AccessControl::class,
                'rules' => [
                    [
                        'actions' => ['index'],
                        'allow' => true,
                        'roles' => ['adminPanel']
                    ],
                    [
                        'actions' => ['update'],
                        'allow' => true,
                        'roles' => ['editTaskListLimit']
                    ]
                ]
            ]

//            [
//                'class' => 'common\filters\RbacFilter',
//                'action_permission' => [
//                    'index' => 'adminPanel',
//                    'view' => 'adminPanel',
//                    'create' => 'adminPanel',
//                    'update' => 'editTaskListLimit',
//                    'delete' => 'adminPanel',
//                ]
//            ],
        ];
    }


    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => User::find(),
            'sort' => ['defaultOrder' => ['id' => SORT_DESC]]
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
        ]);
    }


    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if(Yii::$app->request->method == 'POST'){
            $new_limit = Yii::$app->request->post('User')['tasklist_limit'];
            if(!\Yii::$app->user->can('changeTaskListLimit', ['user' => $model, 'new_limit' => $new_limit])){
                $model->addError('tasklist_limit', 'too many task lists');
                return $this->render('update', [
                    'model' => $model,
                ]);
            }

            $model->tasklist_limit = $new_limit;
            $model->save(false);
            return $this->redirect(['index']);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }


    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }


    protected function findModel($id)
    {
        if (($model = User::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

backend/views/layouts/_sidebar.php
<?php
use yii\helpers\Url;
?>

<!-- Sidebar user panel -->
<div class="user-panel">
    <div class="pull-left image">
        <?php echo \cebe\gravatar\Gravatar::widget(
            [
                'email' => 'username@example.com',
                'options' => [
                    'alt' => '0',
                ],
                'size' => 64,
            ]
        ); ?>
    </div>
    <div class="pull-left info">
        <p><?= \Yii::$app->user->identity->username ?> </p>

        <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
    </div>
</div>


<!--<!-- search form -->-->
<!--<form action="#" method="get" class="sidebar-form">-->
<!--    <div class="input-group">-->
<!--        <input type="text" name="q" class="form-control" placeholder="Search..."/>-->
<!--        <span class="input-group-btn">-->
<!--            <button type='submit' name='seach' id='search-btn' class="btn btn-flat"><i-->
<!--                        class="fa fa-search"></i></button>-->
<!--        </span>-->
<!--    </div>-->
<!--</form>-->
<!-- /.search form -->


<?php

// prepare menu items, get all modules
$menuItems = [];

$favouriteMenuItems[] = ['label' => 'MAIN NAVIGATION', 'options' => ['class' => 'header']];


//$developerMenuItems = [];
//$developerMenuItems[] = [
//    'url' => ['/sub/action/one'],
//    'icon' => 'cog',
//    'label' => 'Sub 1',
//];
//$developerMenuItems[] = [
//    'icon' => 'cog',
//    'label' => 'No Link',
//];
//$developerMenuItems[] = [
//    'icon' => 'cog',
//    'label' => 'Not visible',
//    'visible' => false,
//];
//$developerMenuItems[] = [
//    'icon' => 'cog',
//    'label' => 'Folder',
//    'items' => [
//        [
//            'url' => ['/sub/action/two'],
//            'icon' => 'cog',
//            'label' => 'SubSub 2',
//        ],
//    ],
//];
//$developerMenuItems[] = [
//    'url' => ['/sub/action/three'],
//    'icon' => 'cog',
//    'label' => 'Sub 3',
//];
//$developerMenuItems[] = [
//    'url' => ['/sub/action/param', 'id' => 'a'],
//    'icon' => 'cog',
//    'label' => 'Param A',
//];
//$developerMenuItems[] = [
//    'url' => ['/sub/action/param', 'id' => 'b'],
//    'icon' => 'cog',
//    'label' => 'Param B',
//];


$menuItems[] = [
    'url' => Url::to(['task/index']),
    'icon' => 'cog',
    'label' => 'Task',
];

$menuItems[] = [
    'url' => Url::to(['task-list/index']),
    'icon' => 'cog',
    'label' => 'Task list',
];

$menuItems[] = [
    'url' => Url::to(['user/index']),
    'icon' => 'cog',
    'label' => 'User',
];

$menuItems[] = [
    'url' => Url::to(['auth/logout']),
    'icon' => 'cog',
    'label' => 'LogOut',
];

//$menuItems[] = [
//    #'url' => '#',
//    'icon' => 'cog',
//    'label' => 'Test with items',
//    'items' => $developerMenuItems,
//];

//for ($i = 0; $i < 25; $i++) {
//    $menuItems[] = [
//        'url' => ['/test/auto', 'id' => $i],
//        'icon' => 'cog',
//        'label' => 'Auto '.$i,
//    ];
//}

echo dmstr\widgets\Menu::widget([
    'items' => \yii\helpers\ArrayHelper::merge($favouriteMenuItems, $menuItems),
]);
?>

backend/views/layouts/login.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use common\widgets\Alert;
use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use backend\assets\AppAsset;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>

<div class="wrap">
    <?php
    NavBar::begin([
        'brandLabel' => Yii::$app->name,
        'brandUrl' => Yii::$app->homeUrl,
        'options' => [
            'class' => 'navbar-inverse navbar-fixed-top',
        ],
    ]);
    echo Nav::widget([
        'options' => ['class' => 'navbar-nav navbar-right'],
        'items' => [
            ['label' => 'Home', 'url' => ['/site/index']],
            ['label' => 'About', 'url' => ['/site/about']],
            ['label' => 'Contact', 'url' => ['/site/contact']],
            Yii::$app->user->isGuest ? (
                ['label' => 'Login', 'url' => ['/login']]
            ) : (
                '<li>'
                . Html::beginForm(['/site/logout'], 'post')
                . Html::submitButton(
                    'Logout (' . Yii::$app->user->identity->username . ')',
                    ['class' => 'btn btn-link logout']
                )
                . Html::endForm()
                . '</li>'
            )
        ],
    ]);
    NavBar::end();
    ?>

    <div class="container">
        <?= Breadcrumbs::widget([
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]) ?>
        <?= Alert::widget() ?>
        <?= $content ?>
    </div>
</div>

<footer class="footer">
    <div class="container">
        <p class="pull-left">&copy; My Company <?= date('Y') ?></p>

        <p class="pull-right"><?= Yii::powered() ?></p>
    </div>
</footer>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

backend/views/layouts/main.php
<?php
use dmstr\widgets\Alert;
use yii\helpers\Html;


/* @var $this \yii\web\View */
/* @var $content string */
$this->title = $this->title . ' [Backend]';
dmstr\web\AdminLteAsset::register($this);
?>

<?php $this->beginPage() ?>
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>
    <!-- Ionicons -->
    <link href="//code.ionicframework.com/ionicons/1.5.2/css/ionicons.min.css" rel="stylesheet" type="text/css"/>
    <!-- Theme style -->
    <?php $this->head() ?>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
</head>

<body class="hold-transition skin-black sidebar-mini">
<?php $this->beginBody() ?>

<div class="wrapper">

    <header class="main-header">
        <!-- Logo -->
        <a href="<?= \Yii::$app->homeUrl ?>" class="logo"><?= getenv('APP_TITLE') ?></a>
        <!-- Header Navbar: style can be found in header.less -->
        <nav class="navbar navbar-static-top" role="navigation">
            <!-- Sidebar toggle button-->
            <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
                <span class="sr-only">Toggle navigation</span>
            </a>

        </nav>
    </header>
    <!-- Left side column. contains the logo and sidebar -->
    <aside class="main-sidebar">
        <!-- sidebar: style can be found in sidebar.less -->
        <section class="sidebar">
            <?= $this->render('_sidebar') ?>
        </section>
        <!-- /.sidebar -->
    </aside>

    <!-- Right side column. Contains the navbar and content of the page -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <h1>
                <small><?= $this->title ?></small>
            </h1>
        </section>

        <!-- Main content -->

        <section class="content">
            <?= Alert::widget() ?>
            <?= $content ?>
        </section>
        <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->
    <footer class="main-footer">
        Powered by <strong><a href="http://phundament.com">Phundament 4</a></strong>
    </footer>
</div>
<!-- ./wrapper -->

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>